version: 2.1

orbs:
  react: thefrontside/react@0.1.0

workflows:
  # push workflow will be triggered when a new pull request is created
  push:
    jobs:
      - react/install
      - react/test
          requires:
            - react/install